{
	"version": 1719197939,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tilemap.png",
		"images/fade-sheet0.png",
		"images/casa.png",
		"images/iluminaçãocasa-sheet0.png",
		"images/fundo2-sheet0.png",
		"images/toquenagrama-sheet0.png",
		"images/fundo-sheet0.png",
		"images/fogueira-sheet0.png",
		"images/iluminaçãofogueira-sheet0.png",
		"images/personagem1-sheet0.png",
		"images/basepersonagem-sheet0.png",
		"images/munição-sheet0.png",
		"images/personagem2-sheet0.png",
		"images/jeep-sheet0.png",
		"images/jeep-sheet1.png",
		"images/jeep-sheet2.png",
		"images/zumbi-sheet0.png",
		"media/som de fundo.ogg",
		"media/som de fogueira.ogg",
		"media/som da noite.ogg",
		"media/shotgun.ogg",
		"media/caminhando na grama.ogg",
		"media/caminhar1.ogg",
		"media/caminhar2.ogg",
		"media/cansada.ogg",
		"media/pulo.ogg",
		"media/fala1 - bill .ogg",
		"media/fala inicial - glinda.ogg",
		"media/fala2 - glinda.ogg",
		"media/bocejo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}